<?php

namespace ContainerN5NaKjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YE.U6HB.App\Entity\Seance' shared service.
     *
     * @return \App\Entity\Seance
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YE.U6HB": it needs an instance of "App\\Entity\\Seance" but this type has been excluded in "config/services.yaml".');
    }
}
