<?php

namespace ContainerRIxq7UA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UXj_6sPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uXj.6sP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uXj.6sP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Atelier::index' => ['privates', '.service_locator.wawo2j8', 'get_ServiceLocator_Wawo2j8Service', true],
            'App\\Controller\\Atelier::show' => ['privates', '.service_locator.G9nP4pP', 'get_ServiceLocator_G9nP4pPService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\SeanceController::delete' => ['privates', '.service_locator.YE.U6HB', 'get_ServiceLocator_YE_U6HBService', true],
            'App\\Controller\\SeanceController::edit' => ['privates', '.service_locator.YE.U6HB', 'get_ServiceLocator_YE_U6HBService', true],
            'App\\Controller\\SeanceController::new' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController::delete' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController::edit' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController::index' => ['privates', '.service_locator.wawo2j8', 'get_ServiceLocator_Wawo2j8Service', true],
            'App\\Controller\\WorkshopController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\WorkshopController::show' => ['privates', '.service_locator.G9nP4pP', 'get_ServiceLocator_G9nP4pPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Atelier:index' => ['privates', '.service_locator.wawo2j8', 'get_ServiceLocator_Wawo2j8Service', true],
            'App\\Controller\\Atelier:show' => ['privates', '.service_locator.G9nP4pP', 'get_ServiceLocator_G9nP4pPService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\SeanceController:delete' => ['privates', '.service_locator.YE.U6HB', 'get_ServiceLocator_YE_U6HBService', true],
            'App\\Controller\\SeanceController:edit' => ['privates', '.service_locator.YE.U6HB', 'get_ServiceLocator_YE_U6HBService', true],
            'App\\Controller\\SeanceController:new' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController:delete' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController:edit' => ['privates', '.service_locator.04tykP0', 'get_ServiceLocator_04tykP0Service', true],
            'App\\Controller\\WorkshopController:index' => ['privates', '.service_locator.wawo2j8', 'get_ServiceLocator_Wawo2j8Service', true],
            'App\\Controller\\WorkshopController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\WorkshopController:show' => ['privates', '.service_locator.G9nP4pP', 'get_ServiceLocator_G9nP4pPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Atelier::index' => '?',
            'App\\Controller\\Atelier::show' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\SeanceController::delete' => '?',
            'App\\Controller\\SeanceController::edit' => '?',
            'App\\Controller\\SeanceController::new' => '?',
            'App\\Controller\\WorkshopController::delete' => '?',
            'App\\Controller\\WorkshopController::edit' => '?',
            'App\\Controller\\WorkshopController::index' => '?',
            'App\\Controller\\WorkshopController::new' => '?',
            'App\\Controller\\WorkshopController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Atelier:index' => '?',
            'App\\Controller\\Atelier:show' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\SeanceController:delete' => '?',
            'App\\Controller\\SeanceController:edit' => '?',
            'App\\Controller\\SeanceController:new' => '?',
            'App\\Controller\\WorkshopController:delete' => '?',
            'App\\Controller\\WorkshopController:edit' => '?',
            'App\\Controller\\WorkshopController:index' => '?',
            'App\\Controller\\WorkshopController:new' => '?',
            'App\\Controller\\WorkshopController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
